version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql:///flaskr
      - REDISCLOUD_URL=redis://localhost
      - SECRET_KEY=devnotcompletelyrandomsecretkey


  worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      - DATABASE_URL=postgresql:///flaskr
      - REDISCLOUD_URL=redis://localhost
      - SECRET_KEY=devnotcompletelyrandomsecretkey
      - CELERY_BROKER_URL=redis://redis
      - CELERY_RESULT_BACKEND=redis://redis
      - CELERY_TASK_IGNORE_RESULT=true
    depends_on:
      - redis
      - db


  redis:
    image: redis
    ports:
      - "6379:6379"
  
  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=flaskr
      - POSTGRES_PASSWORD=devnotcompletelyrandomsecretkey
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
  
  seed:
    build: ./db
    profiles: [seed]
    user: postgres
    environment:
      - POSTGRES_DB=flaskr
      - POSTGRES_PASSWORD=devnotcompletelyrandomsecretkey
      - POSTGRES_HOST=db
    restart: "no"
    depends_on:
      - server


volumes:
  db-data:
