version: '3.7'
services:
  server:
    build:
      context: ./flaskr
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - redis
    environment:
      - DATABASE_URL=postgresql://beaver:password@host.docker.internal:5432/flaskr
      - REDISCLOUD_URL=redis://localhost
      - SECRET_KEY=devnotcompletelyrandomsecretkey
      - TRANSFORMERS_CACHE=/cache/worker
      - HF_HOME=/cache/worker

  worker:
    build:
      context: ./celery_worker
      dockerfile: Dockerfile.celery
    environment:
      - DATABASE_URL=postgresql://beaver:password@host.docker.internal:5432/flaskr
      - REDISCLOUD_URL=redis://localhost
      - SECRET_KEY=devnotcompletelyrandomsecretkey
      - CELERY_BROKER_URL=redis://redis
      - CELERY_RESULT_BACKEND=redis://redis
      - CELERY_TASK_IGNORE_RESULT=true
      - TRANSFORMERS_CACHE=/cache/worker
      - HF_HOME=/cache/worker
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"